CREATE TABLE [dbo].[APEXSQL_LOG_OPERATION] (
	[LSN] [char](22) NOT NULL,
	[OPERATION_TYPE] [varchar](128) NULL,
	[OBJECT_NAME] [nvarchar](128) NULL,
	[USER_NAME] [nvarchar](128) NULL,
	[TRANSACTION_ID] [char](13) NULL,
	[TRANSACTION_BEGIN] [datetime] NULL,
	[TRANSACTION_END] [datetime] NULL,
	[TRANSACTION_DESCRIPTION] [nvarchar](500) NULL,
	[ROW_RECONSTRUCTED] [bit] NULL,
	[PAGE_ID] [char](13) NULL,
	[SLOT_ID] [int] NULL,
	[ID_KEY] [nvarchar](1000) NULL,
	[SPID] [smallint] NULL,
	[SERVER] [nvarchar](128) NULL,
	[DATABASE] [nvarchar](128) NULL,
	[TRANSACTION_STATE] [varchar](10) NULL,
	[SCHEMA_NAME] [nvarchar](128) NULL,
	[ROW_PARTIALLY_RECONSTRUCTED] [bit] NULL,
	[ROW_ORDINAL] [smallint] NOT NULL,
	[PARENT_SCHEMA_NAME] [nvarchar](128) NULL,
	[PARENT_OBJECT_NAME] [nvarchar](128) NULL,
	[PREVIOUS_LSN] [char](22) NULL,
	[DURATION] [float] NULL,
	[LOGON_TIME] [datetime] NULL,
	CONSTRAINT [PK_APEXSQL_LOG_OPERATION] PRIMARY KEY CLUSTERED (
		[LSN] ASC,
		[ROW_ORDINAL] ASC
		) WITH (
		PAD_INDEX = OFF,
		STATISTICS_NORECOMPUTE = OFF,
		IGNORE_DUP_KEY = OFF,
		ALLOW_ROW_LOCKS = ON,
		ALLOW_PAGE_LOCKS = ON
		) ON [PRIMARY]
	) ON [PRIMARY]
GO