CREATE TABLE [dbo].[APEXSQL_BEFORE_AFTER_DETAIL] (
	[LSN] [char](22) NOT NULL,
	[DATABASE_ID] [int] NOT NULL,
	[ROW_ORDINAL] [smallint] NOT NULL,
	[LINE_NO] [smallint] NOT NULL,
	[IS_PRIMARY_KEY] [bit] NOT NULL,
	[COLUMN_NAME] [nvarchar](128) NULL,
	[BEFORE] [nvarchar](max) NULL,
	[AFTER] [nvarchar](max) NULL,
	CONSTRAINT [PK_APEXSQL_BEFORE_AFTER_DETAIL] PRIMARY KEY CLUSTERED (
		[LSN] ASC,
		[DATABASE_ID] ASC,
		[ROW_ORDINAL] ASC,
		[LINE_NO] ASC,
		[IS_PRIMARY_KEY] ASC
		) WITH (
		PAD_INDEX = OFF,
		STATISTICS_NORECOMPUTE = OFF,
		IGNORE_DUP_KEY = OFF,
		ALLOW_ROW_LOCKS = ON,
		ALLOW_PAGE_LOCKS = ON
		) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO