CREATE TABLE [dbo].[APEXSQL_BEFORE_AFTER_OPERATION] (
	[LSN] [char](22) NOT NULL,
	[DATABASE_ID] [int] NOT NULL,
	[TIME] [datetime] NULL,
	[OPERATION_TYPE] [varchar](128) NULL,
	[SCHEMA] [nvarchar](128) NULL,
	[TABLE] [nvarchar](128) NULL,
	[USER_NAME] [nvarchar](128) NULL,
	[DURATION] [float] NULL,
	[RECONSTRUCTED] [bit] NULL,
	CONSTRAINT [PK_APEXSQL_BEFORE_AFTER_OPERATION] PRIMARY KEY CLUSTERED (
		[LSN] ASC,
		[DATABASE_ID] ASC
		) WITH (
		PAD_INDEX = OFF,
		STATISTICS_NORECOMPUTE = OFF,
		IGNORE_DUP_KEY = OFF,
		ALLOW_ROW_LOCKS = ON,
		ALLOW_PAGE_LOCKS = ON
		) ON [PRIMARY]
	) ON [PRIMARY]
GO