CREATE TABLE [dbo].[APEXSQL_LOG_OPERATION_DETAIL] (
	[LSN] [char](22) NOT NULL,
	[LINE_NO] [int] NOT NULL,
	[COLUMN_NAME] [nvarchar](128) NULL,
	[COLUMN_TYPE] [nvarchar](128) NULL,
	[OLD_VALUE] [ntext] NULL,
	[NEW_VALUE] [ntext] NULL,
	CONSTRAINT [PK_APEXSQL_LOG_OPERATION_DETAIL] PRIMARY KEY CLUSTERED (
		[LSN] ASC,
		[LINE_NO] ASC
		) WITH (
		PAD_INDEX = OFF,
		STATISTICS_NORECOMPUTE = OFF,
		IGNORE_DUP_KEY = OFF,
		ALLOW_ROW_LOCKS = ON,
		ALLOW_PAGE_LOCKS = ON
		) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO