BULK INSERT APEXSQL_LOG_OPERATION
	FROM 'E:\test\Operations_05-16-2013.sql'
	WITH(DATAFILETYPE = 'widechar')

BULK INSERT APEXSQL_LOG_OPERATION_DETAIL
	FROM 'E:\test\Details_05-16-2013.sql'
	WITH(DATAFILETYPE = 'widechar')
GO